name: Check the source code
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
            cd Code/backend
            npm install
      - name: Code Formatter
        run: |
            cd Code/backend
            npm run format
